### ISSUE TITLE
Not linking to libconfig++.so.11 on Debian 12

### ISSUE THREAD

**Issue by clintonthegeek** [guruthree/palm-calendar-sync2#2]
Hello,

Very neat project, and I was looking forward to playing around with it tonight. Glad to see someone else interested in carrying their calendar around with them on an old Palm. :)

Getting this to compile on Debian 12 was a bit of a chore, but even though I finally managed, it's still throwing an error on execution.

`./sync-calendar2: error while loading shared libraries: libconfig++.so.11: cannot open shared object file: No such file or directory`

I'm guessing that all the little hacks I had to do ended up breaking something in the compilation process.

First of all, I used the source packages and their dependencies from the [JPilot website](https://www.jpilot.org/download/) (the `*_0.12.5-dfsg-2build2_amd64.deb` versions). Seems to have worked great, might throw that hint into your readme.

When it came to `libconfig`, however, it seemed that the development packages in the Debian repos (`libconfig++-dev` is at version 1.5-0.4) kept throwing an error about a missing function:

`class libconfig::Config' has no member named 'setOption'; did you mean 'setOptions'?`

Obviously setOption != setOptions because changing that on line 137 just broke things more, hahaha.

So I just downloaded the [latest source](https://github.com/hyperrealm/libconfig) for libconfig (which is now at 1.7.3) and compiled/installed it with the ol' `./configure`/`make`/ `sudo make install`, and then threw the source into its own folder (called `lib`) in the `palm-calendar-sync2` folder, adding it to `CMakeLists.txt` file with `target_include_directories(sync-calendar2 PUBLIC "." "lib/")`.

After that, `palm-calendar-sync2` compiled great! Yet it can't find the `libconfig++.so.11` file! It's definitely in my `LD_LIBRARY_PATH`, though. Again, I'm guessing it's something to do with how I compiled it, but I haven't been able to figure that out. Is there something obvious I'm missing here?

(And the Apptainer image throws a segfault once the Hotsync starts, but that's a different problem, haha).

**Comment by guruthree** [comment]
Hopefully we can get things working for playtime! Great spot about the availability on JPilot's site, I've added this to the [README.md](https://github.com/guruthree/palm-calendar-sync2/commit/ee3cfb737587d047f6f98aca4ab4a855d1082cf8). Thanks.

Unfortunate to hear about the Apptainer segfaulting. You might have more luck with it if you try a different sync method (e.g., serial if you've been trying USB). I know I had an issue with closing the libusb connection that I had to write a work around for in the code. (It just hung forever...)

For the library not found, does running `ldd` detect the library? I.e.,
```$ LD_LIBRARY_PATH="/path/to/libconfig++.so.11" ldd ./sync-calendar2```
If you should see
```libconfig++.so.11 => /usr/lib64/libconfig++.so.11 (0x00007eff8c8b0000)```
Then `ldd` thinks the library is there but `sync-calendar2` doesn't which sounds like shell shenanigans. If `ldd` doesn't think the library is there that unfortunately also sounds like shell shenanigans, but is probably some arcane buried flag somewhere.

It's probably worth trying to change line 137 to
```cfg.setOptions(libconfig::Config::OptionAutoConvert)```
which should be the equivalent line and hopefully work with the older libconfig. Maybe if that compiles it picks up then the system installed libconfig and avoid the library not found issue.

**Comment by clintonthegeek** [comment]
Okay! Yes, it was just silly shell stuff. Thanks for the hint with `ldd`. But now we're on to a new problem...

**Comment by ecliptik** [comment]
I know this is a closed issue, but I ran into similar problem when building and after following this issue, I was able to build sync-calendar2 on Debian 12 and get past the libconfig++ issue in the following way,

```
# Install Dependencies
sudo apt-get install build-essential git \
 libcurl4-openssl-dev libical-dev libusb-dev autoconf \
 libtool libtool-bin libpopt-dev bison flex autotools-dev \
 automake 

#Remove conflicting libconfig-dev package
sudo apt-get remove libconfig-dev

#Build pilot-link
git clone https://github.com/desrod/pilot-link.git
cd pilot-link
#Patch `configure.ac` from https://aur.archlinux.org/cgit/aur.git/plain/configure-checks.patch?h=pilot-link-git
./autogen.sh
make && sudo make install

#Build libconfig
git clone https://github.com/hyperrealm/libconfig.git
cd libconfig
autoreconf
make && sudo make install

#Reload libary path and continue building palm-calendar-sync2
sudo ldconfig
```

If the libconfig-dev package is installed on Debian, it may cause a conflict with the newer library and removing it avoids this. 

Running ldconfig after installing libconfig from source will reload `/usr/local/lib`, and successfully build and run `sync-calendar2` without errors. Hope this helps anyone else who may run into a similar issue.
