### ISSUE TITLE
Feature Request: Options for Limiting Days to Sync and Excluding Event Notes

### ISSUE THREAD

**Issue by ecliptik** [guruthree/palm-calendar-sync2#6]
I have been using the `FROMYEAR` option in my `datebook.cfg`, however on larger calendars it can still pull in hundreds of events that aren't useful if using as a daily planner, especially at the end of the year.

This can cause issues on older Palms with limited space. For example my Zire m150 has 2MiB of storage, and syncing my work calendar eats up 1.2MiB.

If there was an option like `PREVIOUSDAYS` to sync only the previous X days (eg 7, 30, 14, etc) and including future events it could help control the number of events sync'd and keep the storage and number of records down.

Another option for saving on storage could be an option to exclude the `Note:` of events, and only importing `Start:`, `End:` and `Summary:`. For example a config option of `EVENTNOTE=false`.

**Comment by guruthree** [comment]
Good suggestions and pretty easy to do! I've added `PREVIOUSDAYS` and `SKIPNOTES` in 6620af2 and a95e1a2.

**Comment by ecliptik** [comment]
Re-built and tested the new options out and they work great. The datebook is much smaller now and fits well in the limited space and it syncs much faster than when it was trying to do a whole year. Thank you very much.
